
version: '3'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: awaken
    networks:
      - awaken

  awaken-auth-service:
    build: .
    env_file:
      - Docker.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - awaken

networks:
  awaken: